### PR TITLE
Update triangulate.py

### PR DESCRIPTION
**Pull request by SjoerdBruijn**
Update such that triangulate can be used on data obtained from different models (i.e. with different markers present in each individual data file), as per issue #23

### CODE REVIEW

**Comment by lambdaloop** [comment]
Thank you for taking the time to do this! 

Looking through this, it seems that you pushed only a minor change that's unrelated to using different models? 
Could you have forgotten to push more changes perhaps?

The corresponding [aniposelib pull request](https://github.com/lambdaloop/aniposelib/pull/7) seems really short as well?

**Comment by SjoerdBruijn** [comment]
Actually, this minor edit made that the code could handle datasets generated from multiple models, as it allows for different datafiles to have different markers (and have some markers not-present). It still requires the user to in some way make sure that all 2D data files are placed in the same directory, with correct names. This seemed the quickest fix to me (and Maud handed me the data in this fashion). Same for the aniposelib. It works, but requires the user to take care that the data is ordered in the correct way. For us, this would be sufficient (and I don't know enough about the anipose architecture to think of ways to incorporate the organization of data etc... ).

**Comment by lambdaloop** [comment]
Ah I understand what you're trying to do now. I don't see any issues with this, will merge then. Thank you for your contribution!!

**Comment by SjoerdBruijn** [comment]
Yes, I also did this, but did not find the time to do a PR. Anyway, it seems to be needed if you want seperate networks per camera.

**Pull request merged**
